server: 
    port: ${port:8082}
    
mybatis: 
    type-aliases-package: com.dx.guba.activity.service.internal.model
    mapper-locations: classpath:/mybatis-mappers/*
    
spring: 
  datasource: 
    url: jdbc:mysql://192.168.18.157:3306/guba?useSSL=false
    username: all
    password: 112233
    driver-class-name: com.mysql.jdbc.Driver