server: 
    port: ${port:8085}

spring: 
  rabbitmq:
    host: localhost
    username: guba
    password: guba
    virtual-host: /dev 
  datasource: 
    url: jdbc:mysql://192.168.18.157:3306/guba?useSSL=false
    username: all
    password: 112233
    driver-class-name: com.mysql.jdbc.Driver

mybatis: 
    type-aliases-package: com.dx.guba.post.service.internal.model
    mapper-locations: classpath:/mybatis-mappers/* 