server: 
    port: ${port:8081}
    servlet-path: /api/v1

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30 
    lease-renewal-interval-in-seconds: 10
    
    
mybatis: 
    type-aliases-package: com.dx.post.model
    mapper-locations: classpath:/mybatis-mappers/*
    
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/stock?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver